### ISSUE TITLE
Build Tools

### ISSUE THREAD

**Issue by andrewMacmurray** [foundersandcoders/keep-the-lights-on#11]
Need to figure out how to set elm up, do we use `webpack` (do we need webpack)? How do we do things like include link tags in the head of our document?

**Comment by andrewMacmurray** [comment]
Success! Done without webpack!

this is a great article on how to set up your own html file and embed the main elm program in a div, whilst still watching for changes in the elm files:

https://maximilianhoffmann.com/posts/how-to-compile-elm-files-on-save

**Comment by iteles** [comment]
Any contributions to https://github.com/dwyl/learn-elm/ will of course be super useful for the wider community :wink:

**Comment by andrewMacmurray** [comment]
@iteles I had meant to add the `learn-elm` link to the readme, will pop it up there and consolidate some of the resources in the wiki. How / where do you think it would be best to add them to the dwyl  repo (as there's not much up there just yet)?

**Comment by iteles** [comment]
@andrewMacmurray As you go along!

The way I tend to do it is to have the readme for the `learn-xyz` repo open alongside the project I'm using to learn. Then I just keep adding to it as I go along: I start with a 'Reading list' type section and commit that and then I just keep adding sections as I'm learning. It doesn't have to be perfect, taking people along for the ride through the commit history is pretty awesome!

**Comment by ivanmauricio** [comment]
This issue was moved to keep-the-lights-on/keep-the-lights-on#11
