### ISSUE TITLE
Linter Set Up

### ISSUE THREAD

**Issue by ivanmauricio** [foundersandcoders/keep-the-lights-on#14]
We need to find base `.eslintrc.json` file which we can customise as we go along.

**Comment by iteles** [comment]
On linting, have you seen https://github.com/dwyl/goodparts which @eliascodes @shouston3 @jrans and @SimonLab worked on over the summer?

**Comment by ivanmauricio** [comment]
Thanks @iteles, will have a look into it!

**Comment by ivanmauricio** [comment]
This issue was moved to keep-the-lights-on/keep-the-lights-on#14
