### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by andrewMacmurray** [foundersandcoders/keep-the-lights-on#15]
We could use [`AVA`](https://github.com/avajs/ava), very similar to `tape`

We could use [`Nightwatch`](http://nightwatchjs.org/) for e2e testing

Also this seems like a decent utility for unit testing the frontend:
+ [Elm Test](https://github.com/deadfoxygrandpa/elm-test)
+ [Testing in Elm Article](https://medium.com/@_rchaves_/testing-in-elm-93ad05ee1832#.nu5mu9ty9)

**Comment by iteles** [comment]
If you're using Nightwatch, this might be useful: https://github.com/dwyl/learn-nightwatch

**Comment by ivanmauricio** [comment]
This issue was moved to keep-the-lights-on/keep-the-lights-on#15
