### ISSUE TITLE
Documentation: wiki vs readme

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/keep-the-lights-on#18]
We've had past projects where we have used both the wiki and the readme for our documentation.

Personally, what I've found is that the readme works best because you have a clear commit history and a neat path linking the issues to the correct readme section (through commit messages).

@andrewMacmurray @ivanmauricio Whatever your choice is, I thought it would be good to agree it here so people can refer back to the decision 👍

**Comment by andrewMacmurray** [comment]
Aww but I really like having a wiki! I guess we could do just the readme instead, forces you to be more clear and concise. We'll do just readme

**Comment by iteles** [comment]
@andrewMacmurray This is your project and your choice! I'm just making sure a choice is actually *made* rather than defaulted to 😊

**Comment by ivanmauricio** [comment]
This issue was moved to keep-the-lights-on/keep-the-lights-on#17
