### ISSUE TITLE
Manually Entered Payments

### ISSUE THREAD

**Issue by ivanmauricio** [foundersandcoders/keep-the-lights-on#7]
I want to be able to record payments made outside the app, i.e. xero, etc...

**Comment by iteles** [comment]
Who wants to record this?

Should they be recorded by users?  By admins? 
Recorded by users and approved by admins?

**Comment by andrewMacmurray** [comment]
@iteles we thought it might be best to start without admins (it seems like an unnecessary feature at this point), we're assuming for the initial build that we'll trust everyone will be honest with the amounts they enter in.

**Comment by iteles** [comment]
Not MVP, agreed, particularly if we have #6 and #2 👍

**Comment by ivanmauricio** [comment]
This issue was moved to keep-the-lights-on/keep-the-lights-on#7
