### ISSUE TITLE
In App Payments

### ISSUE THREAD

**Issue by andrewMacmurray** [foundersandcoders/keep-the-lights-on#8]
I'd like to be able to make a payment directly through the app

**Comment by andrewMacmurray** [comment]
Links #4

**Comment by iteles** [comment]
@andrewMacmurray How does this differ from #4?

**Comment by andrewMacmurray** [comment]
Yea they are the same, I think we went along starting with user stories and then features, will tag the other one and close this one

**Comment by ivanmauricio** [comment]
This issue was moved to keep-the-lights-on/keep-the-lights-on#8
